<<?php include("header.html");?>

<table width="900" border="0"><td align="center">
<br>
<p align="left"> <span style="color:white">Modified Class Single Cylinder Ice Enduro Rules 2016</br></br>
General	</br></br>
1.1	Must be 18 years old to race mod enduro	</br>
1.2	Max 5 Drivers per team (no jumping sleds must ride on team you signed up with)</br>	
1.3	Any stock OEM fuel tank is approved	</br>
1.4	Starting order will be randomly generated by the scoring program or drawn from a bucket of clothespins by one member of each team unless otherwise noted.</br></br>

Chassis	</br></br>
2.1	Built 1980 or earlier (1981 model year built in 1980 not allowed)	</br>
2.2	Must have un-altered leaf spring front end 3" ski spreader OK	</br>
2.3	No wideing of front ski spindle frames	</br>
2.4	You may tilt post but it must remain in stock position at bulkhead	</br>
2.5	May alter handlebars and seat for driver comfort	</br>
2.6	Any OEM rear suspension allowed. MAX Travel is 6" measured from swingarm to suspension stops</br> 
with sled off the ground.	</br>
2.7	Must have suspension stops	</br></br>

Engine	</br></br>
3.1	400cc or less single cylinder naturally aspirated engine. No limit on overbore, go till she blows!	</br>
3.2	Tuned pipe is allowed on All motors	</br>
3.3	All exhuast must exit under snowmobile. No side exit of any kind allowed.	</br>
3.4	Must have working silencer, will be checked	</br>
3.5	Any carb allowed	</br>
3.6	Engines must be 1975 or older model OEM snowmobile engine	</br>
3.7	No Stroker Cranks	</br>
3.8	Must have working original fan cooling system bolted to flywheel</br>	
3.9	Ignition-CDI or points	</br></br>

Ski's	</br></br>
4.1	Metal or Plastic Skis</br>	
4.2	5/8" maximum runner height	</br>
4.3	6" steering carbide max, 1 runner only must be in center of ski	</br>
4.4	Carbide no sharper than 60 degree	</br></br>

Clutches	</br></br>
4.1	Any stock primary clutch 1980 or older also 94c, Power bloc, 102c and P85 clutch allowed stock	</br>
4.2	Any secondary clutch allowed no roller clutches of any kind	</br></br>

Track	</br></br>
5.1	Molded rubber only, any size any year </br>
5.2 No cleats, studs must not protrude past the lowest part of the paddle by more than 3/8"	</br></br>

Protests	</br></br>
Race director has final say on all protests, you have 15 minutes to protest a team after the race. 	
You must state your protest to the race director and produce $100 cash. If the protested team	
was determined legal they will receive the $100, if they were illegal they will be disqualified	
and you will be refunded your $100	</br></br>
Registration fees	</br></br>
$250.00 to enter. 	</br></br>
NO REFUNDS	</span></p></td></table>